"""Add correct_count and total_count to LearningProgress

Revision ID: 2a4b8dbfc52a
Revises: 3b43cf3ca3d2
Create Date: 2025-03-21 01:30:22.155800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a4b8dbfc52a'
down_revision = '3b43cf3ca3d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correct_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('total_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('avg_time', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_progress', schema=None) as batch_op:
        batch_op.drop_column('avg_time')
        batch_op.drop_column('total_count')
        batch_op.drop_column('correct_count')

    # ### end Alembic commands ###
